# Generated by backend; explicit imports register SQLAlchemy metadata.
from ..modules.auth import models as _models_5  # noqa: F401
from ..modules.database.audit import AuditEvent as _models_0  # noqa: F401
from ..modules.jobs import models as _models_1  # noqa: F401
from ..modules.planner import models as _models_2  # noqa: F401
from ..modules.projects import models as _models_4  # noqa: F401
from ..modules.users import models as _models_3  # noqa: F401

REGISTERED_MODEL_MODULES = (
    "modules.database.audit.AuditEvent",
    "modules.jobs.models",
    "modules.planner.models",
    "modules.users.models",
    "modules.projects.models",
    "modules.auth.models",
)
