# Generated by backend; explicit imports register SQLAlchemy metadata.
from ..modules.database.audit import AuditEvent as _models_0  # noqa: F401
from ..modules.jobs import models as _models_1  # noqa: F401

REGISTERED_MODEL_MODULES = (
    "modules.database.audit.AuditEvent",
    "modules.jobs.models",
)
